### ISSUE TITLE
Support for Scala 2.13

### ISSUE THREAD

**Issue by sghpjuikit** [lonelyplanet/prometheus-akka-http#12]
Is is possible to use this with Scala 2.13?

**Comment by toddkazakov** [comment]
Not at the moment. There's WIP PR here https://github.com/lonelyplanet/prometheus-akka-http/pull/11. Contributions are welcome.

**Comment by sghpjuikit** [comment]
Ah my bad, I didn't notice the PR.

I suppose we can leave this open as an issue for the 2.13 support.

**Comment by toddkazakov** [comment]
Support for 2.13 has been added
