### ISSUE TITLE
version 0.3.5 is not published for Scala 2.12

### ISSUE THREAD

**Issue by schleichardt** [lonelyplanet/prometheus-akka-http#8]
see 2.12 https://bintray.com/lonelyplanet/maven/prometheus-akka-http/0.3.5#files/com%2Flonelyplanet%2Fprometheus-akka-http_2.12

and 2.11 https://bintray.com/lonelyplanet/maven/prometheus-akka-http/0.3.5#files/com%2Flonelyplanet%2Fprometheus-akka-http_2.11

**Comment by Camsteack** [comment]
Is it possible to have 0.3.5 published for Scala 2.12 ? would be really useful 🙂

**Comment by bneijt** [comment]
This may be related, but could we also get the 2.12 builds on jcenter?
https://jcenter.bintray.com/com/lonelyplanet/ only lists the 2.11 version now, even though the 2.12 is already at your bintray repo https://dl.bintray.com/lonelyplanet/maven/com/lonelyplanet/

**Comment by toddkazakov** [comment]
@Camsteack just released 0.4.0 for scala 2.11 and 2.12. Unfortunately, I'm not sure how to get 2.12 builds on jcenter.

**Comment by bneijt** [comment]
https://blog.bintray.com/2015/10/08/increase-your-maven-packages-exposure-by-adding-it-to-jcenter/

I think there should be a button somewhere in the web interface of bintray, which has been pressed for the 2.11 build but not yet for the 2.12 build.

**Comment by toddkazakov** [comment]
![screenshot from 2019-01-15 12-39-20](https://user-images.githubusercontent.com/5702348/51175319-a277e800-18c2-11e9-8910-23ee63ac05f8.png)

It's being listed as already linked to jcenter
